/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tech_shutu_jni_YuvUtils */

#ifndef _Included_tech_shutu_jni_YuvUtils
#define _Included_tech_shutu_jni_YuvUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tech_shutu_jni_YuvUtils
 * Method:    allocateMemo
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_tech_shutu_jni_YuvUtils_allocateMemo
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     tech_shutu_jni_YuvUtils
 * Method:    rgbToYuvByAlgorithms
 * Signature: ([I[BII)V
 */
JNIEXPORT void JNICALL Java_tech_shutu_jni_YuvUtils_rgbToYuvByAlgorithms
  (JNIEnv *, jclass, jintArray, jbyteArray, jint, jint);

/*
 * Class:     tech_shutu_jni_YuvUtils
 * Method:    rgbToYuvBylibyuv
 * Signature: (Ljava/lang/Object;[B)V
 */
JNIEXPORT void JNICALL Java_tech_shutu_jni_YuvUtils_rgbToYuvBylibyuv
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     tech_shutu_jni_YuvUtils
 * Method:    rgbToYuvWidthScaleBylibyuv
 * Signature: (Ljava/lang/Object;[BIIII)V
 */
JNIEXPORT void JNICALL Java_tech_shutu_jni_YuvUtils_rgbToYuvWidthScaleBylibyuv
  (JNIEnv *, jclass, jobject, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     tech_shutu_jni_YuvUtils
 * Method:    scaleAndRotateYV12ToI420
 * Signature: ([B[BIIIII)V
 */
JNIEXPORT void JNICALL Java_tech_shutu_jni_YuvUtils_scaleAndRotateYV12ToI420
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint, jint, jint, jint);

/*
 * Class:     tech_shutu_jni_YuvUtils
 * Method:    releaseMemo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tech_shutu_jni_YuvUtils_releaseMemo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
